title: "Harshit Kumar"
email: harshit211997@gmail.com
formspree_url: "https://formspree.io/f/mknkdvlj"
timezone: UTC
domain: "harshit211997.github.io"
url: "https://harshit211997.github.io"
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Harshit
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-352KMFB16K

# Authors
authors:
  harshit:
    name: Harshit
    display_name: Harshit Kumar
    avatar: 'assets/images/sal.png'
    email: harshit211997@gmail.com
    web: https://www.harshitkumar.in/
    twitter: https://twitter.com/wellidonthaveone
    description: "Software Engineer at GitHub, author of this blog, ex game developer"

# Social
social:
  instagram: https://www.instagram.com/harshit211997/
  twitter: https://twitter.com/wellidonthaveone

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives